ALTER TABLE `attendance` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `attendance` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `categories` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `categories` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `customers` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `customers` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `departments` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `departments` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `employees` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `employees` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `expenses` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `expenses` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `leaves` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `leaves` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `media` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `media` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `payroll` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `payroll` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `permissions` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `permissions` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `products` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `products` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `products_variant` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `products_variant` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchase` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchase` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchaseItems` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchaseItems` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchaseReturn` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `purchaseReturn` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `raks` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `raks` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `sales` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `sales` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `salesProducts` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `salesProducts` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `salesReturn` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `salesReturn` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `subCategories` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `subCategories` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `unit` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `unit` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `users` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `users` ADD `updated_at` timestamp;--> statement-breakpoint
ALTER TABLE `vendors` ADD `created_at` timestamp;--> statement-breakpoint
ALTER TABLE `vendors` ADD `updated_at` timestamp;